# Generated by Django 3.2 on 2022-09-28 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(blank=True, max_length=1500, null=True)),
                ('tagline', models.CharField(blank=True, max_length=1500, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=1500, null=True)),
                ('segment', models.CharField(blank=True, max_length=1500, null=True)),
                ('business_model', models.CharField(blank=True, max_length=1500, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=1500, null=True)),
                ('founder_name', models.CharField(blank=True, max_length=500, null=True)),
                ('founder_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('lastyear_revenue', models.CharField(blank=True, max_length=50, null=True)),
                ('funded_bootstrapped', models.BooleanField(default=False)),
                ('tech_brief', models.TextField(blank=True, null=True)),
                ('rewards_recognition', models.TextField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.states')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extended_profile',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='extended_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.extendedprofile'),
        ),
    ]
