# Generated by Django 3.2 on 2022-10-01 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_latestnews_whychooseus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='image',
            field=models.ImageField(blank=True, help_text='370X318', null=True, upload_to='LatestNews/'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='timestamp',
            field=models.DateField(default=datetime.date(2022, 10, 1)),
        ),
    ]
